# Generated by Django 3.2.8 on 2021-10-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_b', models.CharField(max_length=256)),
                ('email_b', models.EmailField(max_length=256)),
                ('phone_b', models.CharField(max_length=256)),
                ('comments_b', models.CharField(max_length=256)),
            ],
        ),
    ]
